### ISSUE TITLE
CSS for fullscreen

### ISSUE THREAD

**Issue by Snille** [tosti007/MMM-TouchNavigation#2]
Hi! I think something has changed in the CSS somewhere. I am using the region "fullscreen_below" to set a profile picture with my [Profilepicture module](https://github.com/Snille/MMM-Profilepicture). However, some time ago (maybe a week or two) in the development branch of MM did some changes, because my profilepicture no linger where displayed. I figured out that it is beucase of your (and my own [Modulebar module](https://github.com/Snille/MMM-Modulebar) at the time) that had a CSS entry like this:
```CSS
.region.fullscreen {
    z-index: -1;
}
```
I don't know if this is needed anymore. I have added a "counter" setting in my custom.css to fix it. But others may have the same problem. Is this entry still needed in the CSS for the module? I removed mine for my Modulebar and it works anyway. But I can see that the "transparency" may be a problem... 
What do you think?

**Comment by tosti007** [comment]
As I recall, at the time of making the module pressing buttons did not work properly so it needed that css fix you posted. I also heard that they did something about it in the development branch. However I did not look all too much at it and thought it wouldn't hurt that much to leave it as it was. 

Unfortunately I don't have that much time the comming week, so I will look into it after that. Thank you for letting me know!

**Comment by Snille** [comment]
No problem, It's not a hurry. :) I just entered:
```CSS
.region.fullscreen {
    z-index: 0;
}
```
In my costum.css and it works again.

**Comment by tosti007** [comment]
Just tested and noticed it works without. I commited the change. Can you confirm that it works properly now?

**Comment by Snille** [comment]
I'm not able to for the moment. I'm currently building the frame and therefore have the mirror disassembled.

**Comment by tosti007** [comment]
No problem, I think it works now but I will mark this as resolved once you also say it is

**Comment by Snille** [comment]
I completely forgot about this one. And all works so I guess it's resolved. :) Thank you.
